name = "tales-of-the-shire"
compatibility_date = "2024-12-19"

[build]
command = "npm run build"
output_directory = ".next"

[build.environment]
NODE_VERSION = "18"
NODE_ENV = "production"

[site]
bucket = ".next"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[env.production]
name = "tales-of-the-shire"
compatibility_date = "2024-12-19" 